### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ngangtk** [AMontgomerie/question_generator#11]
Hi, 

May I know where can I download the dataset (qg_train.csv, qg_valid.csv)?

tq.

**Comment by AMontgomerie** [comment]
The datasets are available on the huggingface hub now.
* [question generator training and validation data](https://huggingface.co/datasets/iarfmoose/question_generator)
* [qa evaluator training and validation data](https://huggingface.co/datasets/iarfmoose/qa_evaluator)
