### ISSUE TITLE
datasets are not available 

### ISSUE THREAD

**Issue by omrishsu** [AMontgomerie/question_generator#12]
@AMontgomerie the datasets (qa_eval_train.csv, qa_eval_valid.csv, question_generator/datasets/qg_train.csv and question_generator/datasets/qg_valid.csv) are no longer available in the google drive folder.
Can you please re-share them?

**Comment by AMontgomerie** [comment]
Hi, sorry for the delay. The datasets are available on the huggingface hub now.
* [question generator training and validation data](https://huggingface.co/datasets/iarfmoose/question_generator)
* [qa evaluator training and validation data](https://huggingface.co/datasets/iarfmoose/qa_evaluator)
