### ISSUE TITLE
Error in qg training

### ISSUE THREAD

**Issue by hyssss** [AMontgomerie/question_generator#7]
Hi @AMontgomerie ,

I just found an error in `qg_training.ipynb`. In last cell of `qg_training.ipynb`, the function `train()` should have parameters. Is `SAVED_MODEL_PATH` the same to `TEMP_SAVE_PATH`?

Thanks,
Yu

**Comment by AMontgomerie** [comment]
Hi, sorry for the slow response.

You're right, I must've changed something without rerunning all the cells at some point. I should probably refactor the notebook into a script to avoid this kind of thing.

Yes, `TEMP_SAVE_PATH` should also be replaced with `SAVED_MODEL_PATH`.
